Draft build via Github Actions part 13

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -30,7 +30,18 @@ jobs:
           mkdir buildDbg
           cd buildDbg
           cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=out -DCONAN_DEPS_PATH=/workspace/search-service-dependencies-rel ..
-          make all
+          make install
+
+      - name: Run unit tests
+        run: |
+          cd buildDbg/out/bin
+          ./map_app_search_service_unit_tests --gtest_output="xml.report.xml"
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: "buildDbg/out/bin/report.xml"
 
       - name: Run coverage
         run: |
@@ -38,10 +49,10 @@ jobs:
           make coverage
 
       - name: Publish coverage
-        uses: peaceiris/actions-gh-pages@v3
+        uses: actions/upload-artifact@v3
         with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: buildDbg/tests/unit_tests/coverage
+          name: coverage
+          path: buildDbg/tests/unit_tests/coverage
 
       - name: Build Release
         run: |
@@ -49,3 +60,9 @@ jobs:
           cd buildRel
           cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=out -DCONAN_DEPS_PATH=/workspace/search-service-dependencies-rel ..
           make install
+
+      - name: Publish Release
+        uses: actions/upload-artifact@v3
+        with:
+          name: map-app-search-service-rel
+          path: buildRel/out
